#!/usr/bin/env python3
"""Agent handoff: turn onboarding submissions into working crawler entries.

Reads onboard/queue.jsonl for items with status "pending", and for each:
  1. scaffolds crawler/parsers/<client>.py from a template (TODO selectors +
     the human's notes baked in as guidance),
  2. adds the client to config/sites.yaml,
  3. registers it in crawler/parsers/__init__.py,
  4. marks the queue item "registered" (selectors still need the agent to finalize).

After this, the agent (火哥的绿龙虾) inspects the site, fills the TODO
selectors, then runs:
  python cli.py --client <client> --limit 3 --no-articles   # smoke test
  python cli.py --client <client>                            # full crawl

Run:
  venv/bin/python onboard/process_queue.py
"""
from __future__ import annotations

import json
import os
import re
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
QUEUE = os.path.join(HERE, "queue.jsonl")
PARSERS_DIR = os.path.join(ROOT, "crawler", "parsers")
SITES_YAML = os.path.join(ROOT, "config", "sites.yaml")
INIT_PY = os.path.join(PARSERS_DIR, "__init__.py")


def _parser_template(req: dict) -> str:
    client = req["client"]
    name = req["name"]
    base = req["base_url"]
    list_url = req["list_url"]
    notes = req.get("notes") or "(none)"
    media_source = req.get("media_source") or name
    return f'''"""{name} news/media parser (auto-scaffolded from onboarding form).

List page : {list_url}
Client    : {client}  ({name})
Media src : {media_source}
Human notes: {notes}

Generated by onboard/process_queue.py. Finalize the TODO selectors, then run:
  python cli.py --client {client} --limit 3 --no-articles   # smoke test
  python cli.py --client {client}                            # full crawl
"""
from __future__ import annotations

from bs4 import BeautifulSoup

BASE = "{base}"
LIST_URL = "{list_url}"


def _abs(href: str) -> str:
    if href.startswith("http"):
        return href
    return BASE + href


# TODO: replace with the real container for each news item on the list page.
ITEM_SELECTOR = "TODO_FILL_ME"   # e.g. "div.press-release-listing"


def parse_list(html: str) -> list[dict]:
    soup = BeautifulSoup(html, "lxml")
    items = []
    for box in soup.select(ITEM_SELECTOR):
        a = box.select_one("a")          # TODO: refine to the title link if needed
        if not a or not a.get("href"):
            continue
        date_el = box.select_one("[class*='date']")
        sum_el = box.select_one("p")
        items.append({{
            "title": a.get_text(" ", strip=True),
            "url": _abs(a.get("href", "")),
            "date_raw": date_el.get_text(" ", strip=True) if date_el else "",
            "summary": sum_el.get_text(" ", strip=True) if sum_el else "",
        }})
    return items


# TODO: replace with the real article body container on the detail page.
ARTICLE_SELECTOR = "TODO_FILL_ME"  # e.g. "div.page-descriptiom"


def parse_article(html: str) -> dict:
    soup = BeautifulSoup(html, "lxml")
    desc = soup.select_one(ARTICLE_SELECTOR)
    paras = []
    if desc:
        for p in desc.find_all("p"):
            t = p.get_text(" ", strip=True)
            if t:
                paras.append(t)
    content = "\\n\\n".join(paras)
    h1 = soup.find("h1")
    title = h1.get_text(" ", strip=True) if h1 else ""
    return {{"content": content, "article_title": title}}
'''


def _write_parser(req: dict) -> bool:
    client = req["client"]
    path = os.path.join(PARSERS_DIR, f"{client}.py")
    if os.path.exists(path):
        print(f"  [skip] parser {client}.py already exists")
        return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(_parser_template(req))
    print(f"  [ok] wrote crawler/parsers/{client}.py (TODO selectors)")
    return True


def _update_sites_yaml(req: dict) -> None:
    with open(SITES_YAML, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {"clients": {}}
    clients = cfg.setdefault("clients", {})
    client = req["client"]
    if client in clients:
        print(f"  [skip] {client} already in sites.yaml")
        return
    clients[client] = {
        "name": req["name"],
        "parser": client,
        "list_url": req["list_url"],
        "media_source": req.get("media_source") or req["name"],
        "media_source_url": req.get("media_source_url") or req["list_url"],
        "fetch_articles": bool(req.get("fetch_articles", True)),
        "article_delay": 1.0,
        "limit": 0,
    }
    with open(SITES_YAML, "w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False)
    print(f"  [ok] added {client} to config/sites.yaml")


def _register_in_init(req: dict) -> None:
    client = req["client"]
    with open(INIT_PY, "r", encoding="utf-8") as f:
        src = f.read()
    if f'"{client}"' in src or f"'{client}'" in src:
        print(f"  [skip] {client} already registered in __init__.py")
        return
    # 1) import line after the first `from . import ...`
    src = re.sub(
        r"(from \. import \w+\n)",
        lambda m: (m.group(1) + f"from . import {client}\n") if "from . import sasol" in m.group(1) else m.group(1),
        src, count=1,
    )
    # 2) add to REGISTRY dict
    src = src.replace(
        'REGISTRY = {',
        'REGISTRY = {\n'
        f'    "{client}": {client},',
        1,
    )
    # 3) add to BASE_URL dict
    src = src.replace(
        'BASE_URL = {',
        'BASE_URL = {\n'
        f'    "{client}": "{req["base_url"]}",',
        1,
    )
    with open(INIT_PY, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"  [ok] registered {client} in crawler/parsers/__init__.py")


def _mark_registered(req: dict) -> None:
    if not os.path.exists(QUEUE):
        return
    lines = [l for l in open(QUEUE, encoding="utf-8").read().splitlines() if l.strip()]
    out = []
    for l in lines:
        obj = json.loads(l)
        if obj.get("client") == req["client"] and obj.get("status") == "pending":
            obj["status"] = "registered"
            from datetime import datetime
            obj["registered_at"] = datetime.now().isoformat(timespec="seconds")
        out.append(json.dumps(obj, ensure_ascii=False))
    with open(QUEUE, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + ("\n" if out else ""))


def main() -> int:
    if not os.path.exists(QUEUE):
        print("queue empty (no onboard/queue.jsonl) — nothing to do.")
        return 0
    pending = []
    for line in open(QUEUE, encoding="utf-8").read().splitlines():
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        if obj.get("status") == "pending":
            pending.append(obj)

    if not pending:
        print("no pending submissions.")
        return 0

    print(f"processing {len(pending)} pending submission(s):")
    for req in pending:
        client = req["client"]
        print(f"\n== {client} ({req['name']}) ==")
        if req.get("base_url") and req.get("list_url"):
            _write_parser(req)
            _update_sites_yaml(req)
            _register_in_init(req)
            _mark_registered(req)
            print(f"  -> scaffolded. Agent: finalize TODO selectors in crawler/parsers/{client}.py")
            print(f"     smoke test: python cli.py --client {client} --limit 3 --no-articles")
        else:
            print("  [skip] missing base_url/list_url")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
